In [1]:
import numpy as np

In [13]:
X = np.array([[64.0, 580.0, 29.0], [66.0, 570.0, 33.0], [68.0, 590.0, 37.0], [69.0, 660.0, 46.0], [73.0 , 600.0, 55.0]]).T

In [14]:
X.T

array([[ 64., 580.,  29.],
       [ 66., 570.,  33.],
       [ 68., 590.,  37.],
       [ 69., 660.,  46.],
       [ 73., 600.,  55.]])

In [18]:
mean1 = np.mean(X[0])

In [20]:
mean2 = np.mean(X[1])

In [22]:
mean1

68.0

In [23]:
mean2

600.0

In [17]:
np.sum((X[0] - mean)*(X[0] - mean))/4

11.5

In [24]:
np.sum((X[0] - mean1)*(X[1] - mean2))/4

50.0

In [25]:
np.cov(X)

array([[  11.5 ,   50.  ,   34.75],
       [  50.  , 1250.  ,  205.  ],
       [  34.75,  205.  ,  110.  ]])

In [28]:
from sklearn.decomposition import PCA

In [30]:
pca = PCA(n_components=2)

In [36]:
z = pca.fit_transform(X.T)

In [37]:
z

array([[-21.75169162,  -7.97708662],
       [-30.81578708,  -1.83909853],
       [-10.35810824,  -1.01408628],
       [ 60.12181901,  -4.72901599],
       [  2.80376794,  15.55928742]])

In [40]:
X_approx = pca.inverse_transform(z)

In [45]:
X_approx

array([[ 64.45278032, 580.00778459,  28.84210795],
       [ 66.06664509, 570.00114582,  32.97675974],
       [ 67.22076631, 589.98660274,  37.27173178],
       [ 69.05413006, 660.00093065,  45.98112394],
       [ 73.20567821, 600.0035362 ,  54.92827658]])

In [41]:
X.T

array([[ 64., 580.,  29.],
       [ 66., 570.,  33.],
       [ 68., 590.,  37.],
       [ 69., 660.,  46.],
       [ 73., 600.,  55.]])

In [42]:
X.T.dot(X)

array([[341337., 335781., 347625., 388550., 354267.],
       [335781., 330345., 342009., 382272., 348633.],
       [347625., 342009., 354093., 395794., 360999.],
       [388550., 382272., 395794., 442477., 403567.],
       [354267., 348633., 360999., 403567., 368354.]])

In [43]:
rec_error = np.mean((X.T - X_approx).T.dot(X.T - X_approx))/np.mean(X.T.dot(X))

In [44]:
rec_error

1.1685157435285284e-07