In [2]:
import numpy as np

In [16]:
X = np.array([[64.0, 580.0, 29.0], [66.0, 570.0, 33.0], [68.0, 590.0, 37.0], [69.0, 660.0, 46.0], [73.0 , 600.0, 55.0]]).T

In [17]:
X

array([[ 64.,  66.,  68.,  69.,  73.],
       [580., 570., 590., 660., 600.],
       [ 29.,  33.,  37.,  46.,  55.]])

In [18]:
cov_mat = np.cov(x)

In [19]:
U, S, V = np.linalg.svd(cov_mat, full_matrices = False)

In [20]:
U

array([[-0.04323679,  0.32677925, -0.94411117],
       [-0.98405914, -0.1770992 , -0.01623197],
       [-0.1725056 ,  0.92835941,  0.32922731]])

In [21]:
S

array([1.28813337e+03, 8.31248957e+01, 2.41738454e-01])

In [22]:
k=2

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=k)
z_pca = pca.fit_transform(X)
X_approx_pca = pca.inverse_transform(z_pca)
ratio_pca = np.mean((X-X_approx_pca).T.dot(X-X_approx_pca))/np.mean(X.T.dot(X))
ratio_pca

2.2939657412517168e-33

In [24]:
X_approx_pca

array([[ 64.,  66.,  68.,  69.,  73.],
       [580., 570., 590., 660., 600.],
       [ 29.,  33.,  37.,  46.,  55.]])

In [ ]:
|